version: "2"
services:
  app:
    build: ./app
    container_name: test_api
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    container_name: test_mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: AdmIn@123@123@
    volumes:
      - ./db/login.sql:/docker-entrypoint-initdb.d/login.sql


